# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Complyfix < Formula
  desc "Compliance automation for infrastructure code — scan, fix, and export evidence."
  homepage "https://complyfix.io"
  version "0.0.1-rc.1"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/complyfix/cli-releases/releases/download/v0.0.1-rc.1/complyfix_0.0.1-rc.1_darwin_amd64.tar.gz"
      sha256 "bc3610f536c7be1d4a696510845cbfeaeb211713847a836221d64ede43de0cea"

      define_method(:install) do
        bin.install "complyfix"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/complyfix/cli-releases/releases/download/v0.0.1-rc.1/complyfix_0.0.1-rc.1_darwin_arm64.tar.gz"
      sha256 "3ec57a0d7672c6b3117750a4461786cba08b10d1e070267a9c0b16cc6bc6c9f7"

      define_method(:install) do
        bin.install "complyfix"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/complyfix/cli-releases/releases/download/v0.0.1-rc.1/complyfix_0.0.1-rc.1_linux_amd64.tar.gz"
      sha256 "2b4e6b659cf1d26571e5187800953396994e9a474379425a9993dd4a96d4d8dd"
      define_method(:install) do
        bin.install "complyfix"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/complyfix/cli-releases/releases/download/v0.0.1-rc.1/complyfix_0.0.1-rc.1_linux_arm64.tar.gz"
      sha256 "89a4ca6cad8196a2ae74c748b430a917d80326e0e11c4724a4dbbf989044efdc"
      define_method(:install) do
        bin.install "complyfix"
      end
    end
  end

  test do
    system "#{bin}/complyfix --version"
  end
end
