# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Complyfix < Formula
  desc "Compliance automation for infrastructure code — scan, fix, and export evidence."
  homepage "https://complyfix.io"
  version "1.0.1"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/complyfix/cli-releases/releases/download/v1.0.1/complyfix_1.0.1_darwin_amd64.tar.gz"
      sha256 "67a226dd6e4f7912c01e55d03977eaa2d99f65ee1cc67642a22adddc8d97f7b5"

      define_method(:install) do
        bin.install "complyfix"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/complyfix/cli-releases/releases/download/v1.0.1/complyfix_1.0.1_darwin_arm64.tar.gz"
      sha256 "78667751008a195bba53de774a3d0c104000e9b9a873939513c75079fbb8cf60"

      define_method(:install) do
        bin.install "complyfix"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/complyfix/cli-releases/releases/download/v1.0.1/complyfix_1.0.1_linux_amd64.tar.gz"
      sha256 "f637fc4a31a873879bb465e7401a55d365596979e4b29cf11f9992548deef080"
      define_method(:install) do
        bin.install "complyfix"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/complyfix/cli-releases/releases/download/v1.0.1/complyfix_1.0.1_linux_arm64.tar.gz"
      sha256 "bed66806eec1d3b21154919e6f700a9255938e6e5b432360672046f25bb65314"
      define_method(:install) do
        bin.install "complyfix"
      end
    end
  end

  test do
    system "#{bin}/complyfix --version"
  end
end
