# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Complyfix < Formula
  desc "IaC compliance scanner and fixer — scan Terraform, Helm, and CloudFormation for SOC 2 / HIPAA violations"
  homepage "https://complyfix.io"
  version "1.0.0"
  license "Apache-2.0"

  depends_on "checkov"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/complyfix/complyfix/releases/download/v1.0.0/complyfix_1.0.0_darwin_amd64.tar.gz"
      sha256 "c3152f8ab8dd891e9d5f1c446917604ae58b090aecc44d4f18700c8f424caa07"

      define_method(:install) do
        bin.install "complyfix"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/complyfix/complyfix/releases/download/v1.0.0/complyfix_1.0.0_darwin_arm64.tar.gz"
      sha256 "6f8a94b04e7173e1d04849fbc82fbdb1d640966785528701721acb99e6806858"

      define_method(:install) do
        bin.install "complyfix"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/complyfix/complyfix/releases/download/v1.0.0/complyfix_1.0.0_linux_amd64.tar.gz"
      sha256 "0f1bb6d619630ee14cc4bd82726b4bb5eb2d342f09c3d3e9b350504614802636"
      define_method(:install) do
        bin.install "complyfix"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/complyfix/complyfix/releases/download/v1.0.0/complyfix_1.0.0_linux_arm64.tar.gz"
      sha256 "177b195e264945cf3acf8f818c6cd33923150f238737eefaa7609a7dccaa0681"
      define_method(:install) do
        bin.install "complyfix"
      end
    end
  end

  test do
    system "#{bin}/complyfix", "--version"
  end
end
