# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Complyfix < Formula
  desc "Compliance automation for infrastructure code — scan, fix, and export evidence."
  homepage "https://complyfix.io"
  version "1.0.2"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/complyfix/cli-releases/releases/download/v1.0.2/complyfix_1.0.2_darwin_amd64.tar.gz"
      sha256 "e0097d28e988bd5416496fdcb56c96ed39fd7a87250ac761ea6960de869879c5"

      define_method(:install) do
        bin.install "complyfix"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/complyfix/cli-releases/releases/download/v1.0.2/complyfix_1.0.2_darwin_arm64.tar.gz"
      sha256 "f9a1a4caa7b9366fb3c00fe07da4429e47f71f9ac0293087850c41c367e42896"

      define_method(:install) do
        bin.install "complyfix"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/complyfix/cli-releases/releases/download/v1.0.2/complyfix_1.0.2_linux_amd64.tar.gz"
      sha256 "5a7b560437a57ef325fc7d806270e0eb3a95226077ebb10df05f2aa1f5d573cc"
      define_method(:install) do
        bin.install "complyfix"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/complyfix/cli-releases/releases/download/v1.0.2/complyfix_1.0.2_linux_arm64.tar.gz"
      sha256 "a9e5f3928055afaf925a537463a2a0c5fa086d44b9011f81f6b44da630c3c57b"
      define_method(:install) do
        bin.install "complyfix"
      end
    end
  end

  test do
    system "#{bin}/complyfix --version"
  end
end
